import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "@/components/providers/session-context";
import { useSession } from "@/lib/lucia";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
	const session = await useSession();

    return (
        <html lang="en">
            <body className={inter.className}>
				<SessionProvider value={session}>
					{children}
					<Toaster />
				</SessionProvider>
            </body>
        </html>
    );
}
